queue_rules:
  - name: automerge
    queue_conditions:
      - check-success=Deprecation_Messages_and_Coverage (3.8)
      - "#approved-reviews-by>=1"
      - label=automerge
      - label!=on hold
    merge_conditions:
      - check-success=Deprecation_Messages_and_Coverage (3.8)
    merge_method: squash

pull_request_rules:
  - name: backport
    conditions:
      - label=stable backport potential
    actions:
      backport:
        branches:
<<<<<<< HEAD
          - stable/0.5
=======
          - stable/0.6
  - name: automatic merge on CI success and review
    conditions: []
    actions:
      queue:
>>>>>>> 3162fef (ci(mergify): upgrade configuration to current format (#647))
