# This code is part of Qiskit.
#
# (C) Copyright IBM 2021.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: 'Install Qiskit Optimization'
description: 'Installs Qiskit Optimization on developer mode'

runs:
  using: "composite"
  steps: 
    - run : |
        # install gurobipy
        pip install -i https://pypi.gurobi.com gurobipy
        pip install -e .[cplex,cvx,matplotlib]
        pip install -U -c constraints.txt -r requirements-dev.txt
      shell: bash
